### ISSUE TITLE
Programar el botón para buscar  las preguntas de recuperación de contraseña

### ISSUE THREAD

**Issue by Drowss** [Drowss/Clase#6]
Validar que se ingrese el documento al cual se le va a buscar la contraseña
Validar que el documento sea un dato tipo numérico
Crear la clase usuario con sus 11 propiedades
Solo considerar un password
Buscar las preguntas para recuperar la contraseña

**Comment by Drowsz** [comment]
Me voy a encargar de este issue voy a desarrollarlo.
Pendiente de alguna sugerencia

**Comment by Drowss** [comment]
Listo quedo pendiente de su primero push y de pull request
